### ISSUE TITLE
files get synced and uploaded but no changes on app after refresh 

### ISSUE THREAD

**Issue by ajitrishabh** [orange-cloudfoundry/cf-plugin-sync#6]
Hi,
im running node.js application on cf and i used this plugin to sync my files and folders.
it got synced and whenever i change file it shows uploading file to app/index.js
but after upload i checked on browser it shows previous output not the updated one.
so i tried to `restart ` the app after the changes upload. but not working
then i tried `restage ` but still not working.

below is the code : 

```
const path = require('path')
const express = require('express')
const request = require('request')
const exphbs = require('express-handlebars') 
const app = express()


app.engine('.hbs', exphbs({  
    defaultLayout: 'main',
     extname: '.hbs',
    layoutsDir: path.join(__dirname, 'views/layouts')
  }))
  app.set('view engine', '.hbs')  
  app.set('views', path.join(__dirname, 'views'))  

app.get('/',(request,response)=>{    
    response.render('home',{
        name:'Hi'
    })
})
```

**Comment by ArthurHlt** [comment]
hi @ajitrishabh 

Your nodejs app is actually the server and process needs to be restarted. you actually can't use this plugin on your app.

This plugin altered container and not droplet, when restarting you actually ask to diego to took current droplet and run it again (which lost every modification you've made). Restaging ask to use code send when you pushed the app to recreate droplet.

**Comment by ajitrishabh** [comment]
Thanks. But is there any way so that I only upload the modified files not the entire code base to CF. there is not issue for me to restart the Server just that I want to have updated code.

**Comment by ajitrishabh** [comment]
hi @ArthurHlt  im getting this error
**Application "cfphpapp" is not running on Diego**
pls help
